In [1]:
import torch

In [2]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
x , y

(tensor([1, 2]), tensor([3, 4]))

In [3]:
x.add(y)

tensor([4, 6])

In [4]:
x.add_(y)

tensor([4, 6])

In [5]:
x

tensor([4, 6])

In [6]:
torch.Tensor([1,2,3,4,5,6])

tensor([1., 2., 3., 4., 5., 6.])

In [7]:
torch.Tensor(2,3)

tensor([[-3.7184e+19,  1.4630e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [8]:
t = torch.Tensor([[1,2,3],[4,5,6]])

# 查看已有的形状

In [9]:
t.size()

torch.Size([2, 3])

In [10]:
torch.Tensor(t.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
type(torch.Tensor(1))

torch.Tensor

In [13]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [17]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [20]:
torch.randn(2,3)

tensor([[ 0.5427,  0.2636, -1.1046],
        [ 1.5706, -0.0379,  1.3017]])

In [21]:
x = torch.randn(2,3)

In [23]:
x.size()

torch.Size([2, 3])

In [24]:
x.dim()

2

In [25]:
x.view(3,2)

tensor([[-0.5619, -0.9866],
        [ 1.3763,  0.5977],
        [ 1.3835,  1.6892]])

In [26]:
x.reshape(-1,1)

tensor([[-0.5619],
        [-0.9866],
        [ 1.3763],
        [ 0.5977],
        [ 1.3835],
        [ 1.6892]])

In [43]:
y = x.view(-1)

In [44]:
y.dim()

1

In [45]:
y.size()

torch.Size([6])

In [49]:
z = torch.unsqueeze(y,0)

In [50]:
y.size()

torch.Size([6])

In [51]:
z.dim()

2

In [53]:
y.numel()

6

In [54]:
z.numel()

6

In [55]:
torch.manual_seed(100)

In [56]:
x = torch.randn(2,3)

In [57]:
x

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])

In [58]:
x[:,-1]

tensor([-0.3938, -2.3134])

In [59]:
mask = x>0
torch.masked_select(x,mask)


tensor([0.3607, 0.2429])

In [60]:
mask = x!=0
torch.masked_select(x,mask)

tensor([ 0.3607, -0.2859, -0.3938,  0.2429, -1.3833, -2.3134])

In [62]:
 torch.nonzero(mask)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2]])

In [64]:
mask

tensor([[True, True, True],
        [True, True, True]])

In [65]:
index = torch.LongTensor([[0,1,1]])
index

tensor([[0, 1, 1]])

In [66]:
torch.gather(x,0,index)

tensor([[ 0.3607, -1.3833, -2.3134]])

In [67]:
x

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])

In [68]:
index= torch.LongTensor([[0,1,1],[1,1,1]])

In [69]:
torch.gather(x,1,index)

tensor([[ 0.3607, -0.2859, -0.2859],
        [-1.3833, -1.3833, -1.3833]])

# 广播机制

In [70]:
import numpy as np

In [72]:
A = np.arange(0,40,10).reshape(4,1)
A

array([[ 0],
       [10],
       [20],
       [30]])

In [73]:
B = np.arange(0,3)

In [74]:
B

array([0, 1, 2])

# 把numpy转换为Tensor

In [75]:
AJ = torch.from_numpy(A)
BJ = torch.from_numpy(B)

In [76]:
cj = AJ + BJ
cj

tensor([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]], dtype=torch.int32)

In [79]:
B2 = BJ.unsqueeze(0)
B2

tensor([[0, 1, 2]], dtype=torch.int32)

In [82]:
A2 = AJ.expand(4,3)
A2

tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30]], dtype=torch.int32)

In [84]:
C1 = B2 +B2
C1

tensor([[0, 2, 4]], dtype=torch.int32)

In [85]:
t = torch.randn(1,3)
t1 = torch.randn(3,1)
t2 = torch.randn(1,3)

In [86]:
torch.addcdiv(t,0.1,t1,t2)

C:\Users\window\AppData\Local\Temp\ipykernel_30928\370452565.py:1: UserWarning: This overload of addcdiv is deprecated:
	addcdiv(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
Consider using one of the following signatures instead:
	addcdiv(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out) (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\python_arg_parser.cpp:1519.)
  torch.addcdiv(t,0.1,t1,t2)


tensor([[-0.3055, -0.8318,  1.7063],
        [-0.2760, -0.7448,  1.6001],
        [-0.3374, -0.9256,  1.8209]])

In [87]:
torch.addcmul(t,0.1,t1,t2)

tensor([[-0.2519, -0.8438,  1.7300],
        [-0.0865, -0.7876,  1.6839],
        [-0.4305, -0.9046,  1.7797]])

In [88]:
torch.sigmoid(t)

tensor([[0.4214, 0.2961, 0.8517]])

In [89]:
torch.clamp(t,0,1)

tensor([[0., 0., 1.]])

In [90]:
a = torch.linspace(0,10,6)

In [92]:
a = a.view(2,3)
a

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [93]:
a.sum(dim = 0)

tensor([ 6., 10., 14.])

In [94]:
a.sum(dim = 1)

tensor([ 6., 24.])

In [95]:
a.sum(dim=0,keepdim = True)

tensor([[ 6., 10., 14.]])

In [98]:
a.cumsum(dim = 0)

tensor([[ 0.,  2.,  4.],
        [ 6., 10., 14.]])

In [99]:
x = torch.linspace(0,10,6).view(2,3)
x

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [100]:
torch.max(x)

tensor(10.)

In [101]:
torch.max(x,dim = 0)

torch.return_types.max(
values=tensor([ 6.,  8., 10.]),
indices=tensor([1, 1, 1]))

In [102]:
torch.topk(x,1,dim = 0)

torch.return_types.topk(
values=tensor([[ 6.,  8., 10.]]),
indices=tensor([[1, 1, 1]]))

In [103]:
e = torch.Tensor([1,2,3])
e

tensor([1., 2., 3.])

In [104]:
b = torch.Tensor([1,3,3])
b

tensor([1., 3., 3.])

In [105]:
a.eq(b)

tensor([[False, False, False],
        [False, False, False]])

In [106]:
a.equal(b)

False

In [110]:
a =  torch.tensor([2,3])
b = torch.tensor([3,4])
torch.dot(a,b)

tensor(18)

In [111]:
x = torch.randint(10,(2,3))

In [112]:
x

tensor([[0, 9, 5],
        [7, 3, 9]])